### ISSUE TITLE
Where is the Vault Shield?

### ISSUE THREAD

**Issue by jpdup** [MylioExternal/bugs#18]
Inconsistent icon for the Shield in the Vault section

![image](https://user-images.githubusercontent.com/2709213/48600359-60611300-e920-11e8-8453-cce08134c41f.png)

**Comment by jpdup** [comment]
This got worst in build 5529

The NAS which is my main backup of all my original is no longer in the "Vault" section
![image](https://user-images.githubusercontent.com/2709213/48601539-10387f80-e925-11e8-854b-c69f105f0556.png)

**Comment by mylodeon** [comment]
The NAS shown above is not a Vault, it's just a Selective Sync device.

Protection now means "Is all my photos on all my Vaults". So you can now choose the level of protection you want and we will warn if all of your photos didn't make it to all your Vaults yet. A Vault is effectively the equivalent of a "Personal cloud".

However, a Vault has to be guaranteed to contain all of your library - if you lose everything else and you only have a Vault left, you are guaranteed that you can reconstruct any and all other devices from it.

There is no such guarantee with a Selective Sync device. It's totally ok to have them on your account, but they're not considered Vaults.

There are various things that are different on a Vault than a "Selective Sync device with Originals" including:
* No FDL or MDL settings - even internally.  Vault has to want/have all.
* No "remove on this device"  (Consequence of not having MDLs)
* Scanner in safe mode will bring lost files back instead of marking them as locally deleted
* Replicator will prioritize and prefer Vaults over other devices.

We did consider a special Vault needing only Originals and not Previews/Thumbs, but especially now with HEIC and other new file types, there are so many cases where preview/thumb extraction is specific to only a subset of device types, that you will almost always end up with missing previews/thumbs if you try and reconstruct a device from an Originals-only device - which will break the "Can reconstruct any device from a Vault" guarantee. If we ever get to a state where all device types can parse all originals, we can support an Originals-only Vault, but for now that will set a user up for pretty guaranteed failure.

**Comment by jpdup** [comment]
Why are thumbnails and previews considered important!
I put all my Originals on the NAS, the T & P are byproducts and not valuable in anyway. All they do is slow down and clutter my NAS.

**Comment by mylodeon** [comment]
Because of what I mentioned above about HEIC files?

**Comment by jpdup** [comment]
I could almost agree about your HEIC argument except for the the fact that sometimes/often Mylio does not accurately extract T & P those file HEIC of other file type, so archiving "unusable/bad" T & P is another reason why this exasperate the problem.

**Comment by mylodeon** [comment]
The HEIC files should really only be extraced on Apple devices, not PC's. It's just coincidental that it started "working" (not really) with new codecs - initially HEIC were only tested for Apple.  

The next build you'll get will have the option to disable HEIC generation on Windows, and I want to see if that solves your problem - if so, we'll disable HEIC by default on Windows.

We're also about to introduce a bunch of new file extensions that have no hope of ever getting previews/thumbs generated on Android.

**Comment by jpdup** [comment]
You are actually proving my point.

If all I have is an Android + PC and NAS, then its quite correct to request that my NAS only wants Originals.  Because no T & P will ever be generated for those unsupported files

**Comment by jpdup** [comment]
BTW, I'm seeing the "wrong T & P" for JPG.  and how do you explain that everything was working fine in 3.1 and only started to break in 3.2 ?

**Comment by mylodeon** [comment]
You presumably won’t have a .heic file if you start off with an Android and PC only. 

If you have an HEIC file then most likely you had an iOS device at some point which would have generated the T&P at the time of import.

**Comment by jpdup** [comment]
Not true, a friend or family member can give me a usb key or drive or Cloud link that contains many HEIC files. I import on my PC then what?

In fact it's a very common scenario for Android user to received by email or chat app many photos that I took of them using my iPhone.

**Comment by mylodeon** [comment]
Then, depending on what codec you use Mylio will try to parse it and infinitely hang in the Window/3rd party parsing code stack. 

It’s a common customer reported issue.

I promise I’ll create an O-only Vault feature the moment Mylio can parse all file types on all platforms equally well. At the moment however that gap is becoming bigger, not smaller.

**Comment by jpdup** [comment]
Well in that case, even JPEG needs to be omitted.
it appears that even parsing JPEG is no longer 100% working. See my new bug 
https://github.com/MylioExternal/bugs/issues/31

**Comment by jpdup** [comment]
Closing this
