### ISSUE TITLE
since version 3.2 I'm seeing many wrong Thumbnail and Preview Rotation in the grid view has been hit and miss

### ISSUE THREAD

**Issue by jpdup** [MylioExternal/bugs#31]
Deon you keep on blaming the wrong T & P rendering problem to HEIC, but here's another example of JPEG not rotated correctly.

The photo opens correctly oriented in all Tool, Software and File Explorer.

![image](https://user-images.githubusercontent.com/2709213/48751771-f3f55500-ec3a-11e8-97d7-81c03bc0c11f.png)

Here's the Metadata from Mylio
```
File:
	Created Date : 2018-07-24 22:33:01
	File Size : 1.3 MB
	Filename : C:\mylioJPDup\RoR\Art\JP\Drawings\Misc\IMG_1102.JPG
	Modified Date : 2018-11-19 20:35:25
exif:
	ColorSpace : 1
	ComponentsConfiguration : 
	ComponentsConfiguration[1] : 1
	ComponentsConfiguration[2] : 2
	ComponentsConfiguration[3] : 3
	ComponentsConfiguration[4] : 0
	ExifVersion : 0221
	FlashpixVersion : 0100
	PixelXDimension : 4032
	PixelYDimension : 2268
	SceneCaptureType : 0
tiff:
	Orientation : 1
	ResolutionUnit : 2
	XResolution : 72/1
	YCbCrPositioning : 1
	YResolution : 72/1
xmp:
	CreatorTool : paint.net 4.1.4

```

**Comment by mylodeon** [comment]
Have you figured out if this is specific to Windows yet?

**Comment by jpdup** [comment]
Not sure how to conclude on "specific to Windows"

Since those are JPG, this is the Mylio decoder right ? I do my editing of the JPeg on the Windows machine. So the scenario needs to work on windows.


This use to work in 3.1

**Comment by mylodeon** [comment]
Last you tried, you imported a portrait picture on an iPad and it was working there, and you were going to try sending a file to Windows and import it there. Did this work or not?

I'm not saying it shouldn't work on Windows support - just trying to figure out where the problem is so that we can repro it. 

This hasn't been reported by anybody except for you on new files.  There was a known issues with this on upgrade if you were internal to Mylio and used an interim build that had an upgrade bug (never shipped). But you shouldn't have that.

**Comment by jpdup** [comment]
The scenario you are talking about was for a HEIC file.  These problem that I'm seeing are for New JPG file

I just now looked my iPhone at the same JPG image that is broken on Windows, I made a video to show you how odd things are showing up.

[bug.mov.zip](https://github.com/MylioExternal/bugs/files/2601419/bug.mov.zip)
